
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evnzekifgzjgwvrafxyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bnpla2lmZ3pqZ3d2cmFmeXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NjU1MDIsImV4cCI6MjA1NzQ0MTUwMn0.RtxFsSebxQPV4J_6vHUJZM7XH5WE0kZXY39ow_tXOwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function for working with tables that might not be in the generated types
export function customQuery(table: string) {
  // Cast to any to avoid TypeScript errors with dynamic table names
  return supabase.from(table) as any;
}
